game_center/config/routes.rb
Rails.application.routes.draw do
  root 'gamecenter#index'

  get '/rps' => 'rps#index'
  post '/rps' => 'rps#create'

  get '/connectfour' => 'connectfour#index'
  post '/connectfour' => 'connectfour#create'

  get '/gameover' => 'connectfour#gameover'

  get '/newc4' => 'connectfour#new'
  get '/newrps' => 'rps#new'

end

game_center/app/models/connectfour.rb
class Connectfour
  attr_accessor :board

  def initialize(c4array=nil)
    if c4array
      @board = c4array
    else
      @board = Array.new(7){Array.new}
    end
  end

  def board
    @board
  end

  def make_move(move, player)
    intmove = move.to_i
    place_piece(intmove, player) if is_valid?(intmove)
  end

  def check_win
    horizontal || vertical || search_diagonal || search_other_diagonal || check_draw
  end

  def place_piece(move, player)
    @board[move-1] << player
  end

  def is_valid?(move)
    intmove = move.to_i
    (0..6).include?(intmove-1) && @board[intmove-1].length < 7
  end

# Checks

  def check_victory(last_move)
    last_move = last_move.to_i - 1
    vertical_check(last_move) || horizontal_check(last_move) || diagonal_up_check(last_move) || diagonal_down_check(last_move)
  end

  def vertical_check(last_move)
    last_move = last_move.to_i
    result=true
    0.upto(3) do |i|
     result = false unless (@board[last_move][-1-i]  == @board[last_move][-1])
    end
    result
  end

  def horizontal_check(last_move)
    last_move = last_move.to_i
    result = true
    color = @board[last_move][-1]
    row = @board[last_move].length-1
    same_count = 0
    (0..6).each do |i|
      if @board[i][row] == color
        same_count += 1
        return true if same_count == 4
      else
        same_count=0
      end
    end
    false
  end

  def diagonal_up_check(last_move)
    last_move = last_move.to_i
    (0..6).each do |column|
      (0..5).each do |row|
        color = @board[column][row]
        break unless @board[column+3] && @board[column+3][row+3]
        return true if @board[column+1][row+1] == color && @board[column+2][row+2] == color && @board[column+3][row+3] == color
      end
    end
    false
  end

  def diagonal_down_check(last_move)
    last_move = last_move.to_i
    (0..6).each do |column|
      (0..5).each do |row|
        color = @board[column][row]
        break unless @board[column-3] && @board[column-3][row+3]
        return true if @board[column-1][row+1] == color && @board[column-2][row+2] == color && @board[column-3][row+3] == color
      end
    end
    false
  end

end

game_center/app/models/rps.rb
class Rps < ActiveRecord::Base
  @@choices = ["rock", "paper", "scissors"]

  def initialize
    @victory = {"scissors" => "rock", "rock" => "paper", "paper" => "scissors" }
  end

  def check_win(choice1)
    comp_choice = computer_chooses
    if choice1 == comp_choice
      "Computer choice was: #{comp_choice}, this is a draw"
    elsif @victory[choice1] == comp_choice
      "Computer choice was: #{comp_choice}, computer wins"
    else
      "Computer choice was: #{comp_choice}, player wins"
    end
  end

  def computer_chooses
    @@choices[rand(0..2)]
  end

end

game_center/app/controllers/connectfour_controller.rb
class ConnectfourController < ApplicationController

  def index
    session[:player] = 'X' unless session[:player]

    if session[:board]
      @c4array = session[:board] #array
    else
      @c4array = Connectfour.new.board # board
      session[:board] = @c4array #array
    end
  end

  def create
    @c4board = Connectfour.new(session[:board]) #board
    if @c4board.make_move(params[:connectfourchoices], session[:player]) #board
      if @c4board.check_victory(params[:connectfourchoices])
        flash[:success] = "Player #{session[:player]} wins"
        redirect_to gameover_path
      else
        session[:player] = (session[:player] == 'X' ? 'O' : 'X')
        redirect_to connectfour_path
      end
    else
      flash[:error] = 'Invalid move'
      redirect_to connectfour_path
    end
  end

  def gameover
    @c4array = session[:board]
  end

  def new
    reset_session
    redirect_to connectfour_path
  end

end

game_center/app/controllers/rps_controller.rb
class RpsController < ApplicationController

  def index
    @rps_game = Rps.new
    @playerchoice = session[:choice]
    @winner = @rps_game.check_win(@playerchoice) if @playerchoice
  end

  def create
    session[:choice] = params[:rpsChoices]
    redirect_to rps_path
  end

  def new
    reset_session
    redirect_to rps_path
  end

end

game_center/app/views/connectfour/gameover.html.erb
<%= flash[:success] %>


<%= link_to "New game!", newc4_path %>
<table>
  <% 6.downto(0).each do |row| %>
    <tr>
    <% (0..6).each do |col| %>
    <td>
    <%= @c4array[col][row].nil? ? '-' : @c4array[col][row] %>
    </td>
    <% end %>
    </tr>
  <% end %>
</table>

game_center/app/views/connectfour/index.html.erb
<div class="container">

  <%= flash[:error] %>
  <%= flash[:success] %>
  <div class="row col-md-6 col-md-offset-3">
    <div class="radio-tile col-sm-6 col-sm-offset-3">
      <%= form_tag do %>
        <% (1..7).each do |col| %>
          <div class="radio">
            <label>
              <input type="radio" name="connectfourchoices" id=<%=col%> value=<%="#{col}"%>>Column <%="#{col}"%>
            </label>
          </div>
        <% end %>
    </div>
  </div>

  <div class="row col-sm-6 col-sm-offset-3">
        <input class="btn btn-large btn-success submit-button col-sm-6 col-sm-offset-3" type="submit">
      <% end %>
  </div>

<div class="row col-sm-6 col-sm-offset-3">
  <table class="col-sm-6 col-sm-offset-3 c4-table">

    <% 6.downto(0).each do |row| %>
      <tr>
      <% (0..6).each do |col| %>
      <td>
      <%= @c4array[col][row].nil? ? "-" : @c4array[col][row] %>
      </td>
      <% end %>
      </tr>
      <% end %>
  </table>
</div>

<div class="row col-sm-6 col-sm-offset-3">
<%= link_to "New game!", newc4_path, class: "btn-new-game col-sm-6 col-sm-offset-3 btn btn-large btn-success" %>
</div>

</div>

game_center/app/views/rps/index.html.erb
<div class="container">

  <div class="row col-md-6 col-md-offset-3">
    <h2 class="col-md-6 col-md-offset-3">Player Choices</h2>
  </div>
  <%= form_tag do %>
  <div class="row col-sm-6 col-sm-offset-3">
    <div class = "radio-tile col-sm-6 col-sm-offset-3">

      <div class="radio">
        <label>
          <input type="radio" name="rpsChoices" id="rock" value="rock">Rock
        </label>
      </div>

      <div class="radio">
        <label>
          <input type="radio" name="rpsChoices" id="paper" value="paper">Paper
        </label>
      </div>

      <div class="radio">
        <label>
          <input type="radio" name="rpsChoices" id="scissors" value="scissors">Scissors
        </label>
      </div>

    </div><!-- close radio tile -->
  </div>
  <div class="row col-sm-6 col-sm-offset-3">
    <input type="submit" class="btn btn-large btn-success col-sm-6 col-sm-offset-3 submit-button">
      <% end %>
  </div>

  <div class="row results col-sm-6 col-sm-offset-3">
    <p class = "col-sm-6 col-sm-offset-3"><%= "Player choice was: #{@playerchoice}" %></p>
    <p class="col-sm-6 col-sm-offset-3"><%= @winner %></p>
    <%= link_to "New game!", newrps_path, class: "btn-new-game col-sm-6 col-sm-offset-3 btn btn-large btn-success" %></p>
  </div><!-- close row -->
</div><!-- close view container -->